version: '3.9'

services:
  postgres:
    image: postgres:15.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-main_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-main_database}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  redis:
    image: redis:7.0.7
    restart: always
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:
